### ISSUE TITLE
I can't even open the launcher.

### ISSUE THREAD

**Issue by chaochao8d** [Hyddwn/HyddwnLauncher#22] opened 2019-03-05 02:02 UTC
I was logged into mabi. I afk'ed for a while and both my clinets crash saying there was some sort of NGS threat detected. I closed the game and tried to open the launcher again and I got this error before the startup UI thing even popped up. Any ideas? I've tried both a clean install of the launcher and of the whole mabinogi client. No luck.

Please and thank you,

Date: 3/4/2019 5:56:04 PM
OS: Microsoft Windows NT 6.2.9200.0
Application Directory: C:\Nexon\Library\mabinogi\appdata\
Current Directory: C:\Nexon\Library\mabinogi\appdata
System Folder: C:\WINDOWS\system32
.NET Runtime: v4.0.30319
Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.
   at HyddwnLauncher.MainWindow..ctor(LauncherContext launcherContext)
   at HyddwnLauncher.App.<OnStartup>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at HyddwnLauncher.App.Main()
   at HyddwnLauncher.Program.Main(String[] args)

**Comment by Seeker1437** [comment] 2019-03-05 03:02
It looks like the configuration is damaged,

Try going to

*%localappdata%* (You can press *WIN* + *R* and copy-paste that in and press enter) 

And try deleting *configuration.json*

**Comment by chaochao8d** [comment] 2019-03-05 03:12
![image](https://user-images.githubusercontent.com/48230090/53778414-7683e680-3eb1-11e9-9176-a514a8083778.png)
Still no luck. Thanks for the quick response though!

**Comment by Seeker1437** [comment] 2019-03-05 03:19
Strange then try removing all of the profiles. I suspect that it’s the clientprofile.json that is the cause of the issue if not the launcher’s configuration.

**Comment by chaochao8d** [comment] 2019-03-05 03:37
![image](https://user-images.githubusercontent.com/48230090/53779434-ee9fdb80-3eb4-11e9-927a-2484fb59501c.png)
No luck again. Thanks for your help and insight though!

**Comment by Seeker1437** [comment] 2019-03-05 03:52
Oops sorry I wasn’t clear, can you remove all of the json files.

**Comment by Seeker1437** [comment] 2019-03-25 15:15
Closed as this issue was resolved.

**Closed by Seeker1437** 2019-03-25 15:15 UTC
